### ISSUE TITLE
S1 api docs ?

### ISSUE THREAD

**Issue by daslicht** [Sookhaal/Nel_S1Library#1]
Hello,
Where do I find the API documentation from StudioOne , please ?

**Comment by Sookhaal** [comment]
Hello, there are no API documentation from StudioOne :/ (to my knowledge at least). If you want to interact with StudioOne you'll have to use "hacks" (emulate clicks and typing in code).
You can find more informations on the Presonus forums (https://forums.presonus.com/viewtopic.php?f=152&t=113), feel free to post there too!

**Comment by daslicht** [comment]
Yeah I saw that threre are just user creations no further infos no?
But how would you handle note selections and lets say set the velocity ? or its position in time.

**Comment by Sookhaal** [comment]
As I said, mostly using hacks: image-matching a specific note, clicking on it etc etc, it's pretty ugly unfortunately. I hope Presonus will be able to make a proper API in a future version of StudioOne.

I'm sure you could do something prettier though. I'm quite bad at programming, someone could send 'messages' directly to StudioOne instead of emulating user inputs.

**Comment by daslicht** [comment]
hm wont be x y dependent of the current s1 window states eg info platte enabled etc?

**Comment by Sookhaal** [comment]
It is dependent, indeed, which is why you have to image-match some points (to get an offset for example). If I remember correctly though, there was a problem when you want to interact with an undocked window (Mix for example).

All in all, it's bad & ugly, which is why I don't bother with it anymore, unless I need a specific function.
